-- Migración 004: carga inicial de reuniones desde el Excel (Reuniones Agendadas).
-- Es un solo statement (un INSERT multi-fila) — pegalo entero en el editor Query de Neon.

insert into meetings (id, for_month, meeting_date, company, contact_name, contact_role, linkedin_url, type, channel, status, ae, sqc_value, note, qualified, qualified_by_nacho)
values
('mtg-seed-grupo-schettino-2026-03-01-0', 'MARZO', '2026-03-01', 'Grupo Schettino', NULL, NULL, NULL, 'Inbound', NULL, 'Reunión Completada', 'Jose Ignacio Laguardia', 0.0, NULL, 'No', 'Si'),
('mtg-seed-coorsa-2026-03-02-1', 'MARZO', '2026-03-02', 'Coorsa', NULL, NULL, NULL, 'Inbound', NULL, 'Reunión Completada', 'Jose Ignacio Laguardia', 0.0, NULL, 'No', 'Si'),
('mtg-seed-librerias-gandhi-2026-03-03-2', 'MARZO', '2026-03-03', 'Librerias Gandhi', NULL, NULL, NULL, 'Inbound', NULL, 'Reunión Completada', 'Jose Ignacio Laguardia', 0.0, NULL, 'No', 'Si'),
('mtg-seed-tia-2026-04-15-3', 'ABRIL', '2026-04-15', 'Tia', NULL, NULL, NULL, 'Inbound', '-', 'Reunión Completada', 'Pablo Macedo', 1.0, NULL, 'No', 'Si'),
('mtg-seed-crisa-libbey-2026-04-16-4', 'ABRIL', '2026-04-16', 'Crisa Libbey', 'Cesar Hernandez', 'Director HR', NULL, 'Outbound', 'Linkedin', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-kraft-heinz-2026-04-17-5', 'MAYO', '2026-04-17', 'Kraft Heinz', 'Alberto Araujo', 'CHRO USA', NULL, 'Outbound', 'Linkedin', 'Reunión Completada', 'Pablo Macedo', 2.0, NULL, 'No', 'Si'),
('mtg-seed-coastoil-dynamic-2026-04-23-6', 'MAYO', '2026-04-23', 'Coastoil Dynamic', NULL, NULL, NULL, 'Inbound', '-', 'Reunión Completada', 'Pablo Macedo', 1.0, NULL, 'En proceso', 'Si'),
('mtg-seed-cienogroup-2026-04-28-7', 'MAYO', '2026-04-28', 'Cienogroup', NULL, NULL, NULL, 'Inbound', '-', 'Discovery BDR', 'Jose Ignacio Laguardia', 0.0, 'Fue solo conmigo', 'No', 'Si'),
('mtg-seed-dollar-general-2026-04-28-8', 'MAYO', '2026-04-28', 'Dollar General', NULL, NULL, NULL, 'Inbound', '-', 'Reunión Completada', 'Pablo Macedo', 1.0, NULL, 'En proceso', 'Si'),
('mtg-seed-leonali-2026-04-29-9', 'MAYO', '2026-04-29', 'Leonali', NULL, NULL, NULL, 'Inbound', '-', 'No-show', 'Jose Ignacio Laguardia', 0.0, 'No-show', 'No', 'Si'),
('mtg-seed-saint-gobain-2026-05-05-10', 'MAYO', '2026-05-05', 'Saint-Gobain', 'Paulina Bielma', 'Gerente HR', NULL, 'Outbound', 'Llamada', 'No-show', 'Jose Ignacio Laguardia', 0.0, 'No-show', 'No', 'Si'),
('mtg-seed-zubale-2026-05-05-11', 'MAYO', '2026-05-05', 'Zubale', NULL, NULL, NULL, 'Inbound', '-', 'Reunión Completada', 'Jose Ignacio Laguardia', 0.0, NULL, 'No', 'Si'),
('mtg-seed-whirlpool-2026-05-06-12', 'MAYO', '2026-05-06', 'Whirlpool', 'Julian Jaidar', 'TA Manager', NULL, 'Outbound', 'Whatsapp', 'Cancelled', 'Jose Ignacio Laguardia', 0.0, 'Me canceló la reunión', 'No', 'Si'),
('mtg-seed-dana-incorporated-2026-05-07-13', 'MAYO', '2026-05-07', 'Dana Incorporated', 'Edgardo Valadez', 'HR Ops Manager', NULL, 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-grupo-coste-o-2026-05-18-14', 'JUNIO', '2026-05-18', 'Grupo Costeño', 'Julian Mora', 'Gerente Nacional de Reclutamiento y Selección', 'https://www.linkedin.com/in/juan-juli%C3%A1n-mora-castro-238023138', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-celestica-2026-05-25-15', 'JUNIO', '2026-05-25', 'Celestica', 'Jorge Lazo', 'Director RRHH', 'https://www.linkedin.com/in/jorgelazo', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-celestica-2026-05-27-16', 'JUNIO', '2026-05-27', 'Celestica', 'Victor Olguin', 'Human Resources Business Partner', 'https://www.linkedin.com/in/victor-olguin-garcia-16b064148', 'Outbound', 'Linkedin', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-metalsa-2026-05-29-17', 'JULIO', '2026-05-29', 'Metalsa', 'Cassandra Barcenas', 'Talent Acquisition Multisite Coordinator', 'https://www.linkedin.com/in/sobarcenas', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, 'Se agendo demo', 'Si', 'Si'),
('mtg-seed-traxi-n-2026-05-29-18', 'JULIO', '2026-05-29', 'Traxión', 'Jose Luis Lugo', 'Director IT HR', 'https://www.linkedin.com/in/joseluislugosuarez', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-grupo-gayosso-2026-05-29-19', 'JULIO', '2026-05-29', 'Grupo Gayosso', 'Isela Montenegro', 'Directora de Tecnología', 'https://www.linkedin.com/in/isela-montenegro-591967112', 'Outbound', 'Email', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-frisa-2026-06-05-20', 'AGOSTO', '2026-06-05', 'Frisa', 'Ivan Arellano', 'Especialista en Reclutamiento', 'https://www.linkedin.com/in/ivan-arellano-jmz', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'Si', 'Si'),
('mtg-seed-igsa-2026-06-09-21', 'AGOSTO', '2026-06-09', 'IGSA', 'Gabriela Mota', 'Jefe de Atracción de Talento', 'https://www.linkedin.com/in/gabriela-mota-montiel-2556a6b3', 'Inbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'Si', 'Si'),
('mtg-seed-dmx-2026-06-10-22', 'AGOSTO', '2026-06-10', 'dmX', 'Lily Romero', 'Head of People BP', 'https://www.linkedin.com/in/lily-romero-vela', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-grupo-rica-2026-06-12-23', 'AGOSTO', '2026-06-12', 'Grupo Rica', 'Edwin Ramirez', 'Gerente de Reclutamiento', 'https://www.linkedin.com/in/edwin-alberto-ramirez-morales-097284a8', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'No', 'Si'),
('mtg-seed-metalsa-2026-06-22-24', 'AGOSTO', '2026-06-22', 'Metalsa', 'Jesus Angel Sanchez Ramirez
Karen Muniz', 'Manager of HR Digital, People Analytics & SSC
People Analytics Analyst', 'https://www.linkedin.com/in/jesusrmz98', 'Outbound', 'Linkedin', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, 'No se unio Jesus porque esta de vacaciones pero dejo a cargo a Karen', 'Si', 'Si'),
('mtg-seed-dmx-2026-06-17-25', 'SEPTIEMBRE', '2026-06-17', 'dmX', 'Jose Leon', 'Gerente de Reclutamiento', 'https://www.linkedin.com/in/jos%C3%A9-miguel-le%C3%B3n-pe%C3%B1uelas-001a6b1a3', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-metalsa-2026-06-23-26', 'SEPTIEMBRE', '2026-06-23', 'Metalsa', 'Marco Antonio Valverde Salinas', 'Head of Digital Innovation', 'https://www.linkedin.com/in/marco-antonio-valverde-salinas-a949b6108', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-traxi-n-2026-06-24-27', 'SEPTIEMBRE', '2026-06-24', 'Traxión', 'Ivan Winkler', 'Gerente de Desarrollo Organizacional Nacional', 'https://www.linkedin.com/in/iv%C3%A1n-alejandro-winkler-j%C3%A1uregui-9b59a681', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'En proceso', 'Si'),
('mtg-seed-viakable-2026-06-30-28', 'OCTUBRE', '2026-06-30', 'Viakable', 'Julian Jaidar Lara', 'Lider de Reclutamiento', 'https://www.linkedin.com/in/julian-jaidar-9a4a04b9', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, 'Muy buena reunión, altas chances de avanzar', 'Si', 'Si'),
('mtg-seed-the-palace-company-2026-07-08-29', 'OCTUBRE', '2026-07-08', 'The Palace Company', 'Montserrat Aleman', 'Directora de Atracción de Talento', 'https://www.linkedin.com/in/monserrat-alem%C3%A1n-84514415b', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, 'No va a avanzar con ella por el momento', 'No', 'Si'),
('mtg-seed-grupo-ortiz-2026-07-10-30', 'OCTUBRE', '2026-07-10', 'Grupo Ortiz', 'Joaquin Baturoni', 'CHRO', 'https://www.linkedin.com/in/joaquinbaturoni', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, 'Para Retencion', 'En proceso', 'Si'),
('mtg-seed-pisa-farmaceutica-2026-07-14-31', 'NOVIEMBRE', '2026-07-14', 'Pisa Farmaceutica', 'Fiorella Mendoza
Ana Karima Yeme
Vanessa Barocio', 'Directoras de HR', NULL, 'Outbound', 'Llamada/Emails/Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, 'Para Retención', 'En proceso', 'Si'),
('mtg-seed-biogenesis-bago-2026-07-20-32', 'NOVIEMBRE', '2026-07-20', 'Biogenesis Bago', 'Mariana Forlenza
Guadalupe Molina
Cesar Liebre
Pablo Soto', 'Muchas personas de diferentes equipos', NULL, 'Inbound', 'Email', 'Reunión Completada', 'Jose Ignacio Laguardia', 0.0, 'No es fit', 'No', 'Si'),
('mtg-seed-sizzling-platter-2026-07-24-33', 'NOVIEMBRE', '2026-07-24', 'Sizzling Platter', 'Brenda Segura', 'HR Director', 'https://www.linkedin.com/in/brenda-segura-vazquez-rh/', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Juli Tabakman', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-costco-2026-08-12-34', 'NOVIEMBRE', '2026-08-12', 'Costco', 'Carlos Iniestra', 'HR Director', 'https://www.linkedin.com/in/carlos-iniestra-78316317', 'Outbound', 'Mail', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-colgate-palmolive-2026-08-11-35', 'DICIEMBRE', '2026-08-11', 'Colgate Palmolive', 'Andres Ramirez', 'Talent & Employee Experience Supervisor', 'https://www.linkedin.com/in/andr%C3%A9s-ram%C3%ADrez-sep-', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'En proceso', 'Si'),
('mtg-seed-grupo-coste-o-2026-08-13-36', 'DICIEMBRE', '2026-08-13', 'Grupo Costeño', 'Julian Mora', 'Gerente Nacional de Reclutamiento y Selección', 'https://www.linkedin.com/in/juan-juli%C3%A1n-mora-castro-238023138', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'En proceso', 'Si'),
('mtg-seed-grupo-multisistemas-2026-08-13-37', 'DICIEMBRE', '2026-08-13', 'Grupo Multisistemas', 'Gabriel Rodriguez Trejo', 'Director Corporativo Operaciones', 'https://www.linkedin.com/in/gabriel-rodr%C3%ADguez-trejo-b848b452', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-circle-k-2026-08-18-38', 'DICIEMBRE', '2026-08-18', 'Circle K', 'Edgar de la Parra', 'Director de Servicios y HR', 'https://www.linkedin.com/in/edgar-de-la-parra-escamilla-8b6a25170', 'Outbound', 'Linkedin', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'No', 'Si'),
('mtg-seed-dmx-2026-08-20-39', 'ENERO', '2026-08-20', 'dmX', 'Jose Leon', 'Gerente de Reclutamiento', 'https://www.linkedin.com/in/jos%C3%A9-miguel-le%C3%B3n-pe%C3%B1uelas-001a6b1a3', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'En proceso', 'Si'),
('mtg-seed-mazda-2026-08-20-40', 'ENERO', '2026-08-20', 'Mazda', 'Victor Lara', 'Assistant Manager', 'https://www.linkedin.com/in/alan-gonz%C3%A1lez-camacho-98a71219b', 'Outbound', 'Llamada', 'Cancelled', 'Jose Ignacio Laguardia', NULL, NULL, 'No', 'Si'),
('mtg-seed-grupo-multisistemas-2026-08-25-41', 'ENERO', '2026-08-25', 'Grupo Multisistemas', 'Alejandra Nava', 'Directora Corporativa de HR', NULL, 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-i-am-hospitality-2026-08-25-42', 'ENERO', '2026-08-25', 'I Am Hospitality', 'Alan Gonzalez', 'Gerente de HR', 'https://www.linkedin.com/in/alan-gonz%C3%A1lez-camacho-98a71219b', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-pentaf-n-2026-08-26-43', 'FEBRERO', '2026-08-26', 'Pentafón', 'Juan Pablo Campo Ocastro', 'Innovation and Transformation Manager', 'https://www.linkedin.com/in/juan-pablo-castro-ocampo', 'Outbound', 'Linkedin', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'Si'),
('mtg-seed-alpla-group-2026-08-28-44', 'FEBRERO', '2026-08-28', 'Alpla Group', 'Karla Ballesteros', 'HR Sr Manager', 'https://www.linkedin.com/in/m-karla-ballesteros-direcci%C3%B3n-de-rh-y-transformavion-organizacional-2b80a947', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'En proceso', 'Si'),
('mtg-seed-whirlpool-2026-09-01-45', 'FEBRERO', '2026-09-01', 'Whirlpool', 'Anali Tirado', 'TA Manager', NULL, 'Outbound', 'Llamada', 'Cancelled', 'Jose Ignacio Laguardia', NULL, NULL, 'No', 'No'),
('mtg-seed-servifacil-2026-09-03-46', 'FEBRERO', '2026-09-03', 'Servifacil', 'Edgar Ramirez Ortiz', 'HR Director', 'https://www.linkedin.com/in/edgarrh74', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'En proceso', 'No'),
('mtg-seed-sedecafe-2026-09-03-47', 'MARZO', '2026-09-03', 'Sedecafe', 'Carlos Velazquez', 'People Director', 'https://www.linkedin.com/in/carlosvelazquezmartinez', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'En proceso', 'No'),
('mtg-seed-gestamp-2026-09-07-48', 'MARZO', '2026-09-07', 'Gestamp', 'Alfredo Burado', 'HR Manager', 'https://www.linkedin.com/in/alfredo-burado-baez-74182b54', 'Outbound', 'Llamada', 'Cancelled', 'Jose Ignacio Laguardia', NULL, NULL, 'No', 'No'),
('mtg-seed-alpla-group-2026-09-08-49', 'MARZO', '2026-09-08', 'Alpla Group', 'Crysser Estrada', NULL, 'https://www.linkedin.com/in/cryss-e-8b78214b', 'Outbound', 'Llamada', 'No-show', 'Jose Ignacio Laguardia', NULL, NULL, 'No', 'No'),
('mtg-seed-grupomar-2026-09-09-50', 'MARZO', '2026-09-09', 'Grupomar', 'Alejandra Ramirez', 'Jefe de Atracción de Talento', 'https://www.linkedin.com/in/alejandra-ramirez-913984185', 'Outbound', 'Llamada', 'Cancelled', 'Jose Ignacio Laguardia', NULL, NULL, 'No', 'No'),
('mtg-seed-i-am-hospitality-2026-09-09-51', 'MARZO', '2026-09-09', 'I Am Hospitality', 'Manuel Rojas', 'HR Director', NULL, 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'Si', 'No'),
('mtg-seed-pasteleria-neufeld-2026-09-09-52', 'MARZO', '2026-09-09', 'Pasteleria Neufeld', 'Alejandro Navarro', 'Gerente de HR', 'https://www.linkedin.com/in/javier-alejandro-navarro-cedillo-2a3a7b135', 'Outbound', 'Whatsapp', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'En proceso', 'No'),
('mtg-seed-grupo-opera-2026-09-10-53', 'MARZO', '2026-09-10', 'Grupo Opera', 'Luis Manuel Mejía Gómez', 'Coordinador de RRHH', NULL, 'Inbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 1.0, NULL, 'En proceso', 'No'),
('mtg-seed-coma-super-willys-2026-09-10-54', 'MARZO', '2026-09-10', 'Coma Super Willys', 'Julian Mena
Gerardo Jimenez', 'HR Director
HR Manager', 'https://www.linkedin.com/in/julian-jimenez-112164252', 'Outbound', 'Llamada', 'Reunión Completada', 'Jose Ignacio Laguardia', 2.0, NULL, 'En proceso', 'No'),
('mtg-seed-agrana-2026-09-14-55', NULL, '2026-09-14', 'Agrana', 'Zugey Alvarado', 'HR Manager', 'https://www.linkedin.com/in/zugey-esmeralda-alvarado-alvarado-55816264', 'Outbound', 'Llamada', 'Reunión Agendada', 'Jose Ignacio Laguardia', NULL, NULL, NULL, 'No'),
('mtg-seed-leadec-2026-09-17-56', 'MARZO', '2026-09-17', 'Leadec', 'Samuel Butron', 'HR Director', 'https://www.linkedin.com/in/samuel-butr%C3%B3n-cruz-01752b23', 'Outbound', 'Llamada', 'Reunión Agendada', 'Jose Ignacio Laguardia', NULL, NULL, NULL, 'No'),
('mtg-seed-operadora-merco-s-57', NULL, NULL, 'Operadora Merco', 'Aline Cornejo', 'HR Ops Manager', NULL, 'Outbound', 'Llamada', 'Reunión Agendada', 'Juli Tabakman', NULL, NULL, NULL, 'No')
on conflict (id) do nothing;
